language: python
python:
  - "3.8"
  # - "nightly"
  # TODO: add nightly back when this issue is fixed: https://github.com/cython/cython/issues/3266
arch:
  - arm64
addons:
  apt:
    sources:
      - sourceline: 'ppa:openjdk-r/ppa'
      - sourceline: 'deb http://www.apache.org/dist/cassandra/debian 311x main'
        key_url: &apache-key https://www.apache.org/dist/cassandra/KEYS
      - sourceline: 'deb-src http://www.apache.org/dist/cassandra/debian 311x main'
        key_url: *apache-key
    packages:
      - cython3
      - openjdk-8-jdk
      - cassandra
services:
  - cassandra
  - mongodb
install:
  - sudo apt-get update && sudo apt-get install -y lsb-release && sudo apt-get clean all
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
  - sudo apt-get install gnupg
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
  - lsb_release -dc
  - ls /etc
  - ls /etc/apt 
  - ls /etc/apt/sources.list.d/
  - sudo touch /etc/apt/sources.list.d/mongodb-org-4.4.list
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
  - sudo apt-get update
  - sudo ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && export DEBIAN_FRONTEND=noninteractive && sudo apt-get install -y tzdata && sudo dpkg-reconfigure --frontend noninteractive tzdata
  - sudo apt-get install -y mongodb-org=4.4.8
  - echo "mongodb-org hold" | sudo dpkg --set-selections
  - echo "mongodb-org-server hold" | sudo dpkg --set-selections
  - echo "mongodb-org-shell hold" | sudo dpkg --set-selections
  - echo "mongodb-org-mongos hold" | sudo dpkg --set-selections
  - echo "mongodb-org-tools hold" | sudo dpkg --set-selections
  - ps --no-headers -o comm 1 
  - echo ====================mongodb service starts============================================
  - sudo systemctl unmask mongod
  - sudo service mongod start
  - sudo service mongod status
  - echo ====================mongodb service started============================================
  # Disable Cassandra optional extensions (faster testing).
  - export CASS_DRIVER_NO_EXTENSIONS=1
  - pip install -e .[test]
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' || $TRAVIS_PYTHON_VERSION == '3.7' || $TRAVIS_PYTHON_VERSION == '3.8' || $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then pip install -e .[experimental_aio]; fi
before_script:
  - bash travis/wait_for_cassandra.sh
script:
  # Run non aio tests first because Python versions before 3.6 does not support aio.
  - export DO_TEST_CASSANDRA=true
  - nosetests --exclude-dir=test/aio
  # Run aio tests.
  - export DO_TEST_MONGO=true
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' || $TRAVIS_PYTHON_VERSION == '3.7' || $TRAVIS_PYTHON_VERSION == '3.8' || $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then nosetests test.aio; fi
